# Generated by Django 3.1.1 on 2020-09-13 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='is_same_street',
            field=models.BooleanField(default=False),
        ),
    ]
